name: switch PORT
on: workflow_dispatch
jobs:

  buildSwitch:
      runs-on: ubuntu-latest
      container: devkitpro/devkita64:latest
      steps:
        - name: Checkout Project Repository
          uses: actions/checkout@v4
        
        - name: Install Haxe 4.3.4
          run: |
            apt-get update
            apt-get install -y wget git neko libgc-dev
            
            echo === DOWNLOADING HAXE FROM GITHUB ===
            wget https://github.com/HaxeFoundation/haxe/releases/download/4.3.4/haxe-4.3.4-linux64.tar.gz
            mkdir haxe_temp
            tar -xf haxe-4.3.4-linux64.tar.gz -C haxe_temp
            cp -r haxe_temp/haxe_*/* /usr/local/bin/
            echo =========
            echo === UPDATING HAXELIB ===
            mkdir -p ~/haxelib
            haxelib --always --quiet setup ~/haxelib
            haxelib --global --always --quiet update haxelib
            echo =========
            
            echo === HAXE VERSION ===
            haxe --version
            echo =========
        
        - name: Install DevKitPro dependencies
          run: |
            echo === SYNCING DEVKITPRO REPOS ===
            sudo sed -i 's/#DisableSandbox/DisableSandbox/g' /etc/pacman.conf 2>/dev/null || true
            dkp-pacman -Sy --noconfirm --disable-download-timeout
            
            echo === INSTALLING SWITCH LIBRARIES ===
            dkp-pacman -S --needed --noconfirm --noconfirm --disable-download-timeout \
              switch-bzip2 switch-cmake switch-curl switch-flac \
              switch-freetype switch-glad switch-glm switch-harfbuzz \
              switch-libdrm_nouveau switch-libjpeg-turbo switch-libmodplug \
              switch-libogg switch-libopus switch-libpng switch-libvorbis \
              switch-libvorbisidec switch-libwebp switch-mesa switch-mpg123 \
              switch-openal-soft switch-opusfile switch-pkg-config switch-sdl2 \
              switch-sdl2_gfx switch-sdl2_image switch-sdl2_mixer \
              switch-sdl2_net switch-sdl2_ttf switch-tools switch-zlib \
              switch-liblua51
        
        - name: Install Haxe libraries
          run: |
            echo === INSTALLING HAXE LIBRARIES ===
            haxelib --always --quiet install format
            haxelib --always --quiet install hxp
            haxelib --always --quiet git lime https://github.com/Slushi-Github/lime-nx.git
            haxelib --always --quiet git hxcpp https://github.com/Slushi-Github/hxcpp-nx.git
            haxelib --always --quiet git hx_libnx https://github.com/Slushi-Github/hx_libnx.git
            echo =========
        
        - name: Setup and build hxcpp
          run: |
            echo === SETUP CUSTOM HXCPP ===
            cd ~/haxelib/hxcpp/git/tools/hxcpp
            haxe compile.hxml
            cd -
            echo =========

        - name: Purge Linux Desktop Backends, X11, and Linux Audio in SDL
          run: |
            echo "=== CLEANING LIME OPENAL BACKENDS FOR SWITCH ==="
            find ~/haxelib/ -name "Build.xml" -exec sed -i '/<file name="alc\/backends\/alsa.cpp"/d' {} +
            find ~/haxelib/ -name "Build.xml" -exec sed -i '/<file name="alc\/backends\/pulseaudio.cpp"/d' {} +
            find ~/haxelib/ -name "Build.xml" -exec sed -i '/<file name="alc\/backends\/oss.cpp"/d' {} +
            find ~/haxelib/ -name "Build.xml" -exec sed -i '/<file name="alc\/backends\/jack.cpp"/d' {} +
            find . -name "Build.xml" -exec sed -i '/<file name="alc\/backends\/alsa.cpp"/d' {} +
            find . -name "Build.xml" -exec sed -i '/<file name="alc\/backends\/pulseaudio.cpp"/d' {} +
            find . -name "Build.xml" -exec sed -i '/<file name="alc\/backends\/oss.cpp"/d' {} +
            find . -name "Build.xml" -exec sed -i '/<file name="alc\/backends\/jack.cpp"/d' {} +
            find ~/haxelib/ -name "alsa.cpp" -exec sh -c 'echo "// Bypassed" > "{}"' \;
            find ~/haxelib/ -name "pulseaudio.cpp" -exec sh -c 'echo "// Bypassed" > "{}"' \;
            find ~/haxelib/ -name "oss.cpp" -exec sh -c 'echo "// Bypassed" > "{}"' \;
            find ~/haxelib/ -name "jack.cpp" -exec sh -c 'echo "// Bypassed" > "{}"' \;
            echo "=== FORCE DISABLING LINUX X11 WINDOWING & AUDIO IN SDL ==="
            find ~/haxelib/ -name "SDL_config_linux.h" -exec sed -i 's/#define SDL_VIDEO_DRIVER_X11 1/#define SDL_VIDEO_DRIVER_X11 0/g' {} +
            find ~/haxelib/ -name "SDL_config_linux.h" -exec sed -i 's/#define SDL_AUDIO_DRIVER_ALSA 1/#define SDL_AUDIO_DRIVER_ALSA 0/g' {} +
            find ~/haxelib/ -name "SDL_config_linux.h" -exec sed -i 's/#define SDL_AUDIO_DRIVER_PULSEAUDIO 1/#define SDL_AUDIO_DRIVER_PULSEAUDIO 0/g' {} +
            find ~/haxelib/ -name "SDL_config_linux.h" -exec sed -i 's/#define SDL_AUDIO_DRIVER_ESD 1/#define SDL_AUDIO_DRIVER_ESD 0/g' {} +
            find ~/haxelib/ -name "SDL_config_linux.h" -exec sed -i 's/#define SDL_AUDIO_DRIVER_ARTS 1/#define SDL_AUDIO_DRIVER_ARTS 0/g' {} +
            find ~/haxelib/ -name "SDL_config_linux.h" -exec sed -i 's/#define SDL_AUDIO_DRIVER_OSS 1/#define SDL_AUDIO_DRIVER_OSS 0/g' {} +
            find ~/haxelib/ -name "SDL_config.h" -exec sed -i 's/#define SDL_VIDEO_DRIVER_X11 1/#define SDL_VIDEO_DRIVER_X11 0/g' {} +
            find ~/haxelib/ -name "SDL_config.h" -exec sed -i 's/#define SDL_AUDIO_DRIVER_ALSA 1/#define SDL_AUDIO_DRIVER_ALSA 0/g' {} +
            find ~/haxelib/ -name "Build.xml" -exec sed -i '/<file name="src\/video\/x11\//d' {} +
            find ~/haxelib/ -name "Build.xml" -exec sed -i '/<file name="src\/audio\/alsa\//d' {} +
            find ~/haxelib/ -name "Build.xml" -exec sed -i '/<file name="src\/audio\/pulse\//d' {} +
            find ~/haxelib/ -name "Build.xml" -exec sed -i '/<file name="src\/audio\/arts\//d' {} +
            find ~/haxelib/ -name "Build.xml" -exec sed -i '/<file name="src\/audio\/esd\//d' {} +
            find . -name "Build.xml" -exec sed -i '/<file name="src\/video\/x11\//d' {} +
            find . -name "Build.xml" -exec sed -i '/<file name="src\/audio\/alsa\//d' {} +
            echo "========= PATCH COMPLETE ========="
        
        - name: Build Lime for Switch
          run: |
            echo === REBUILDING LIME FOR SWITCH ===
            haxelib run lime rebuild switch -Dswitch -v
            echo =========
        
        - name: Skip SScript setup mode
          run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> ~/settings.cocoa
        
        - name: Create Version Tag
          run: echo "${{github.run_id}}" > VERSION
        
        - name: Compile for Switch
          run: |
            echo === COMPILING PROJECT FOR SWITCH ===
            haxelib run lime build Project.xml switch --app-version="4.0.0-${{ github.run_id}}" -D officialBuild
            echo =========
        
        - name: Verify Build Success
          run: |
            if ! ls export/release/switch/bin/*.nro 1> /dev/null 2>&1; then
              echo "::error::.nro file not found."
              exit 1
            fi
        
        - name: Publish Artifact
          uses: actions/upload-artifact@v4.3.4
          with:
            name: switchBuild
            path: export/release/switch/bin/*.nro
